version: 2.1

jobs:
  cypress-run:
    docker:
      - image: circleci/node:16-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npx cypress run --headless --browser chrome --config baseUrl=https://www.saucedemo.com

workflows:
  build-and-test:
    jobs:
      - cypress-run