version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:12.14.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run Cypress tests
          command: |
            npm run cy:run
          environment:
            CYPRESS_baseUrl: https://www.saucedemo.com
            
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main